services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_ROOT_PASSWORD: 'T1m1t1*root'
    ports:
      - '3306:3306'
    volumes:
      - "dbunittest:/var/lib/mysql"
      - "./internal/platform/database/schema/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql"
volumes:
  dbunittest:
