CREATE TABLE IF NOT EXISTS users (
    `id`  INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `age`  INTEGER UNSIGNED NOT NULL,
    `random` VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    `id`  INTEGER UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `title` VARCHAR(50) NOT NULL,
    `author`  INTEGER UNSIGNED NOT NULL
);