// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package database

type Book struct {
	ID     int32
	Title  string
	Author int32
}

type User struct {
	ID     int32
	Name   string
	Age    int32
	Random string
}
